DBHost: "172.31.253.73"
DBPort: 3306
DBUser: "root"
DBPassword: "wsxedc"
DBName: "hello_schema"
DBConnectionPoolSize: 5
DBQueryTimeoutMillis: 5000
ServerPort: 8080
ServerSocketTimeoutMillis: 60000
ThreadPoolSize: 5
