DBHost: "172.31.253.73"
DBPort: 3306
DBUser: "root"
DBPassword: "wsxedc"
DBName: "sajge_db"
DBConnectionPoolSize: 5
DBQueryTimeoutMillis: 5000

serverPort: 8080
serverSocketTimeoutMillis: 60000
threadPoolSize: 5
